AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy s3 and VPCEndpoint
#----------------------------------------------
Parameters:
  Environment:
    Type: String
    AllowedPattern: "[a-zA-Z0-9=-@+?[?]?<?>._]*"
    ConstraintDescription: Can contain only ASCII characters.
    Description: (required) Environment name
  #------------------
  CfnRoleArn:
    Type: String
    Description: (required) Arn of IAM Role for Cfn 
  #------------------
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: Environment
        Parameters: 
          - Environment
          - CfnRoleArn
#----------------------------------------------
Resources:

  #------------------VPC Endpoint
  S3VpcEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${Environment}-VpcFunc-VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      RouteTableIds:
        - Fn::ImportValue: !Sub ${Environment}-VpcFunc-PrivateSubnet1RouteTableId
        - Fn::ImportValue: !Sub ${Environment}-VpcFunc-PrivateSubnet2RouteTableId
        - Fn::ImportValue: !Sub ${Environment}-VpcFunc-PublicSubnetRouteTableId
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:*'
            Resource:
              # Allow connections to the Amazon Linux yum repositories
              - "arn:aws:s3:::packages.*.amazonaws.com/*"
              - "arn:aws:s3:::repo.*.amazonaws.com/*"
              # Allow connections to the Amazon Linux2 yum repositories
              - "arn:aws:s3:::amazonlinux.*.amazonaws.com/*"
              # Allow connections to s3 buckets for CloudFormation custom resource request or a wait condition
              # - !Sub "arn:aws:s3:::cloudformation-custom-resource-response-${AWS::Region}"   # allow trafic to buckes
              # - !Sub "arn:aws:s3:::cloudformation-custom-resource-response-${AWS::Region}/*" # allow trafic to buckes
              # - !Sub "arn:aws:s3:::cloudformation-waitcondition-${AWS::Region}"              # waiting condition
              # - !Sub "arn:aws:s3:::cloudformation-waitcondition-${AWS::Region}/*"            # waiting condition
              # Allow SSM
              - !Sub "arn:aws:s3:::aws-ssm-${AWS::Region}/*"
              - !Sub "arn:aws:s3:::aws-windows-downloads-${AWS::Region}/*"
              - !Sub "arn:aws:s3:::region-birdwatcher-prod/*"
              - !Sub "arn:aws:s3:::patch-baseline-snapshot-${AWS::Region}/*"

              # For ECR
              - !Sub "arn:aws:s3:::prod-${AWS::Region}-starport-layer-bucket/*"

#Outputs:
#  S3BucketTempFileId:
#    Description: name of S3BucketTempFile
#    Value: !Ref S3BucketTempFile
#    Export:
#      Name: !Sub ${AWS::StackName}-S3BucketTempFileId
#  S3BucketTempFileArn:
#    Description: arn of S3BucketTempFile
#    Value: !GetAtt S3BucketTempFile.Arn
#    Export:
#      Name: !Sub ${AWS::StackName}-S3BucketTempFileArn
