AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy EKS Cluster
#----------------------------------------------
Parameters:
  Environment:
    Type: String
    AllowedPattern: "[a-zA-Z0-9=-@+?[?]?<?>._]*"
    ConstraintDescription: Can contain only ASCII characters.
    Description: (required) Environment name
#----------------------------------------------
Resources:
  # K8s Manager(User)
  K8sHighAuthorityPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Sub "${Environment}-K8sHighAuthorityPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowEKSCluster"
            Effect: Allow
            Action:
              - eks:*
            Resource: "*"
          - Sid: "AllowPassRoleForCreateClusters"
            Effect: Allow
            Action:
              - iam:GetRole
              - iam:PassRole
            Resource: "*"
          - Sid: "OnlyThisPoCEnvironment"
            Effect: Allow
            Action:
              - cloudformation:Describe*
              - cloudformation:List*
            Resource: "*"
      Roles:
        - Fn::ImportValue: !Sub ${Environment}-Iam-HighAuthorityInstanceRoleName
  #--------
  K8sManagerPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Sub "${Environment}-K8sManagerPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowUpdateClusterVersionOnly"
            Effect: Allow
            Action:
              - eks:UpdateClusterVersion
              - eks:Describe*
              - eks:List*
            Resource: "*"
          - Sid: "AllowDescribeEc2"  #設定上必要となるEC2情報を取得するため
            Effect: Allow
            Action:
              - "ec2:Describe*"
            Resource: "*"
          - Sid: "AllowControlWorkerNodeEc2Instances"
            Effect: Allow
            Action:
              - "ec2:TerminateInstances"
            Resource: "*"
            Condition:
              StringLike:
                ec2:ResourceTag/Name: "*EksCluster-Worker-Nodes"
      Roles:
        - Fn::ImportValue: !Sub ${Environment}-Iam-ManagerInstanceRoleName

#Outputs:
#  #---------------- EC2 Instance
#  EksClusterId:
#    Description: Eks Cluster ID
#    Value: !Ref EksCluster
#    Export:
#      Name: !Sub ${AWS::StackName}-EksClusterId