apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    app: httpd-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: httpd-pod
  type: ClusterIP