AWSTemplateFormatVersion: '2010-09-09'
Description: Application VPC peering commonVPC between operationVPC
#----------------------------------------------
Parameters:
  Environment:
    Type: String
    AllowedPattern: "[a-zA-Z0-9=-@+?[?]?<?>._]*"
    ConstraintDescription: Can contain only ASCII characters.
    Description: (required) Environment name
  Subsystem:
    Type: String
    Description: (required) sub-system name
  System:
    Type: String
    Description: (required) System name
  #------------------
  ExternalVpcStack:
    Type: String
    Description: (required)External VPC SecurityGroup Stack
  FunctionVpcStack:
    Type: String
    Description: (required)Function VPC SecurityGroup Stack
  #------------------
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: Environment
        Parameters: 
          - Environment
          - Subsystem
          - System
      -
        Label: 
          default: General
        Parameters: 
          - ExternalVpcStack
          - FunctionVpcStack
#----------------------------------------------
Resources:
  #------------------ VPC Peering
  VpcPeering:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${Environment}-${FunctionVpcStack}-VpcId
      PeerVpcId: 
        Fn::ImportValue: !Sub ${Environment}-${ExternalVpcStack}-VpcId
      Tags:
        - Key: Name
          Value: VPCPeer-Function2External
        - Key: Environment
          Value: !Ref Environment
        - Key: Subsystem
          Value: !Sub ${Subsystem}
        - Key: System
          Value: !Sub ${System}
  #------------------ Add routings
  #--- FunctionVPC
  AddRouteDestExternalVpcToFunctionRouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Sub ${Environment}-${FunctionVpcStack}-RouteTableId
      DestinationCidrBlock:
        Fn::ImportValue: !Sub ${Environment}-${ExternalVpcStack}-VpcCidr
      VpcPeeringConnectionId: !Ref VpcPeering
  #--- ExternalVPC
  AddRouteDestFunctionVpcToFExternalPublicRouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Sub ${Environment}-${ExternalVpcStack}-PublicSubnetRouteTableId
      DestinationCidrBlock:
        Fn::ImportValue: !Sub ${Environment}-${FunctionVpcStack}-VpcCidr
      VpcPeeringConnectionId: !Ref VpcPeering
  AddRouteDestFunctionVpcToFExternalPrivateSubnet1RouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Sub ${Environment}-${ExternalVpcStack}-PrivateSubnet1RouteTableId
      DestinationCidrBlock:
        Fn::ImportValue: !Sub ${Environment}-${FunctionVpcStack}-VpcCidr
      VpcPeeringConnectionId: !Ref VpcPeering
  AddRouteDestFunctionVpcToFExternalPrivateSubnet2RouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Sub ${Environment}-${ExternalVpcStack}-PrivateSubnet2RouteTableId
      DestinationCidrBlock:
        Fn::ImportValue: !Sub ${Environment}-${FunctionVpcStack}-VpcCidr
      VpcPeeringConnectionId: !Ref VpcPeering